version: "3"

services:
  amqp:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
      - 5672:5672

  producer:
    build:
      dockerfile: ./docker/producer.Dockerfile
      context: .
    env_file:
      - env/producer.env
    volumes:
      - "./app:/usr/app/app"
    depends_on:
      - amqp
    command: npm run start:producer

  consumer:
    build:
      dockerfile: ./docker/consumer.Dockerfile
      context: .
    env_file:
      - env/consumer.env
    volumes:
      - "./app:/usr/app/app"
      - "./logs:/usr/app/logs"
    depends_on:
      - amqp
    command: npm run start:consumer
